# Generated by Django 4.2 on 2023-05-31 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('mileage', models.IntegerField(blank=True, default=0, null=True)),
                ('steering', models.CharField(blank=True, max_length=5, null=True)),
                ('make', models.CharField(blank=True, max_length=50, null=True)),
                ('product_model', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel', models.CharField(max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('product_state', models.CharField(blank=True, max_length=50, null=True)),
                ('chasis_number', models.CharField(blank=True, max_length=20, null=True)),
                ('engine_number', models.CharField(blank=True, max_length=20, null=True)),
                ('product_year', models.DateField(blank=True, null=True)),
                ('product_color', models.CharField(blank=True, max_length=20, null=True)),
                ('transmission', models.CharField(blank=True, max_length=20, null=True)),
                ('first_registration_year', models.DateField(blank=True, null=True)),
                ('number_of_doors', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_seats', models.IntegerField(blank=True, default=0, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=50, null=True)),
                ('drive', models.CharField(blank=True, max_length=50, null=True)),
                ('m_spec', models.CharField(blank=True, max_length=20, null=True)),
                ('engine_capacity', models.CharField(blank=True, max_length=20, null=True)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('max_capacity', models.CharField(blank=True, max_length=20, null=True)),
                ('images', models.ImageField(upload_to='photos/products')),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_class', models.CharField(choices=[('color', 'color'), ('size', 'size'), ('brand', 'brand'), ('fuel', 'fuel')], max_length=100)),
                ('variation_value', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('review', models.TextField(blank=True, max_length=500)),
                ('rating', models.FloatField()),
                ('ip', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(max_length=255, upload_to='store/products_gallery')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'productgallery',
                'verbose_name_plural': 'product gallery',
            },
        ),
    ]
