# Generated by Django 4.2 on 2023-06-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation_class',
            new_name='variation_category',
        ),
    ]
