# Generated by Django 4.2 on 2023-06-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_logo',
            field=models.ImageField(blank=True, upload_to='photos/logos'),
        ),
    ]
